module.exports = ['La 1',
	'La 2',
	'Antena 3',
	'Cuatro',
	'Cuatro HD',
	'Telecinco',
	'Telecinco HD',
	'La Sexta',
	'A3Series',
	'Nova',
	'Neox',
	'Mega',
	'Divinity',
	'Real Madrid TV',
	'Paramount Channel',
	'Disney Channel',
	'Disney Channel',
	'24h',
	'Teledeporte',
	'Teledeporte HD',
	'13TV',
	'FDF',
	'Telemadrid - Madrid (MD)',
	'La Otra - Madrid (MD)',
	'Russia Today Español',
	'Boing'
]
